

before_install:
#- curl -s https://packagecloud.io/install/repositories/prometheus-deb/release/script.deb.sh | sudo bash
#- sudo apt-get install prometheus=2.1.0-1
# ----------------
#- sudo curl -L https://packagecloud.io/prometheus-deb/release/gpgkey | apt-key add -
#- sudo echo 'deb https://packagecloud.io/prometheus-deb/release/ubuntu/ xenial main' > /etc/apt/sources.list.d/prometheus.list
#- sudo apt-get update
#- sudo apt-get install prometheus
# ----------------
- sudo useradd --no-create-home --shell /bin/false prometheus
- sudo useradd --no-create-home --shell /bin/false node_exporter
- sudo mkdir /etc/prometheus
- sudo mkdir /var/lib/prometheus
- sudo chown prometheus:prometheus /etc/prometheus
- sudo chown prometheus:prometheus /var/lib/prometheus
- cd ~
- curl -LO https://github.com/prometheus/prometheus/releases/download/v2.0.0/prometheus-2.0.0.linux-amd64.tar.gz
- sha256sum prometheus-2.0.0.linux-amd64.tar.gz
- tar xvf prometheus-2.0.0.linux-amd64.tar.gz
- sudo cp prometheus-2.0.0.linux-amd64/prometheus /usr/local/bin/
- sudo cp prometheus-2.0.0.linux-amd64/promtool /usr/local/bin/
- sudo chown prometheus:prometheus /usr/local/bin/prometheus
- sudo chown prometheus:prometheus /usr/local/bin/promtool
- sudo cp -r prometheus-2.0.0.linux-amd64/consoles /etc/prometheus
- sudo cp -r prometheus-2.0.0.linux-amd64/console_libraries /etc/prometheus
- sudo chown -R prometheus:prometheus /etc/prometheus/consoles
- sudo chown -R prometheus:prometheus /etc/prometheus/console_libraries
- rm -rf prometheus-2.0.0.linux-amd64.tar.gz prometheus-2.0.0.linux-amd64

script:
- cd $TRAVIS_BUILD_DIR
- ./promtool_check.sh